#!/bin/sh

. ./image-env.sh

podman tag ${NOTEBOOK}:${GIT_HASH} $REGISTRY/$REGISTRY_USER_ID/${NOTEBOOK}:${GIT_HASH}
podman tag ${NOTEBOOK}:${GIT_HASH} $REGISTRY/$REGISTRY_USER_ID/${NOTEBOOK}:${VERSION}

podman tag ${RUNTIME}:${GIT_HASH} $REGISTRY/$REGISTRY_USER_ID/${RUNTIME}:${GIT_HASH}
podman tag ${RUNTIME}:${GIT_HASH} $REGISTRY/$REGISTRY_USER_ID/${RUNTIME}:${VERSION}

podman push $REGISTRY/$REGISTRY_USER_ID/${NOTEBOOK}:${GIT_HASH}
podman push $REGISTRY/$REGISTRY_USER_ID/${NOTEBOOK}:${VERSION}

podman push $REGISTRY/$REGISTRY_USER_ID/${RUNTIME}:${GIT_HASH}
podman push $REGISTRY/$REGISTRY_USER_ID/${RUNTIME}:${VERSION}
